name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Чек-аут репозитория
        uses: actions/checkout@v3

      - name: Настройка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest pydantic

      - name: Запуск тестов Таблиц 3 и 4 (Универсальные вагоны)
        run: |
          python -m pytest tests/test_full_calculation.py -v -s

      - name: Запуск тестов Таблицы 5 (Специализированный подвижной состав)
        run: |
          python -m pytest tests/test_table_5_full.py -v -s
      
      - name: Запуск тестов Таблицы 6 (Наливные грузы в цистернах)
        run: |
          python -m pytest tests/test_table_6.py -v -s

      - name: Запуск тестов Таблицы 7 (Диагностика)
        run: |
          python -c "import tests.test_table_7"
          python -m pytest tests/test_table_7.py -v -s

      - name: Запуск тестов Правила 3.2.2 (Порожние приватные вагоны)
        run: |
          python -m pytest tests/test_rule_porojniy.py -v -s

      - name: Запуск тестов Правила 3.2.6 (Груженый автопоезд, Перевозка автопоезда, Порожний полуприцеп)
        run: |
          python -m pytest tests/test_rule_3_2_6.py -v -s

      - name: Запуск тестов Правила 3.2.6 (Гружёный İNV)
        run: |
          python -m pytest tests/test_rule_3_3_1.py -v -s

      - name: Запуск тестов Правила 3.2.6 (Порожний İNV)
        run: |
          python -m pytest tests/test_rule_3_3_2.py -v -s

      - name: Запуск тестов Правила Танк контейнеров груженных и порожних
        run: |
          python -m pytest tests/test_rule_3_4_3_1.py -v -s

      - name: Запуск тестов дизель-генератора
        run: |
          python -m pytest tests/test_diesel_generator.py -v -s

      - name: Запуск тестов дизель-генератора контейнер
        run: |
          python -m pytest tests/test_containers_next.py -v -s

      - name: Запуск тестов Таблицы 11 и Негабаритных грузов (п. 3.5)
        run: |
          pytest tests/test_table_11_oversized.py -v -s

      - name: Запуск тестов Таблицы 12 опасные грузы
        run: |
          pytest tests/test_table_12_dangerous.py -v -s

      - name: Запуск тестов Таблицы 13 опасные грузы
        run: |
          pytest tests/test_table_13_dangerous.py -v -s

      - name: Запуск тестов на своих осях
        run: |
          pytest tests/test_section_3_7_rolling_stock.py -v -s

      - name: Запуск тестов на своих осях
        run: |
          pytest tests/test_section_na_svoix_osax.py -v -s
